"""Grounded Q&A over the data the console already shows.

The rule this module exists to enforce: **the model never produces a number.** Every figure
it can mention is computed here, in deterministic Python, from Postgres and the cached Flex
statement, and handed to Claude as a read-only snapshot. Claude's job is to find the right
number in that snapshot and explain it — not to calculate, estimate, or recall one.

That is why the snapshot is aggregated server-side (top underlyings, per-month totals, a
handful of recent rows) rather than shipping 3,000 raw trades and hoping the model adds them
up correctly. If a question needs a figure the snapshot does not contain, the correct answer
is "that isn't in the data I can see" — the system prompt says so explicitly, and the UI
tells the user the same thing.

Unconfigured (no ANTHROPIC_API_KEY) is a normal state, not an error: the endpoint reports
configured=false and the widget explains what to add.
"""
from __future__ import annotations

import logging
import os
from collections import defaultdict
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field
from sqlalchemy import text

log = logging.getLogger("chat")

MODEL = os.getenv("CHAT_MODEL", "claude-opus-5")
# An identity-linked API key must say which workspace it is acting in; a plain key ignores
# this. Sent as a default header so every call carries it.
WORKSPACE_ID = os.getenv("ANTHROPIC_WORKSPACE_ID") or None
MAX_TOKENS = int(os.getenv("CHAT_MAX_TOKENS", "6000"))
# How much history the widget may replay. Long chats mostly re-ask the same snapshot, so a
# short window keeps cost predictable without hurting follow-up questions.
MAX_HISTORY = 10
# Looking a figure up in a JSON blob is not a reasoning problem. Measured against the two
# questions that matter (keeping real apart from demo; refusing to invent), low effort gave
# the same answers as the default in half the wall time — and because ~6k snapshot tokens
# dominate the bill, effort buys latency here far more than it buys money.
EFFORT = os.getenv("CHAT_EFFORT", "low")

SYSTEM = """You are the analyst built into a private SPX iron-condor trading console. You \
answer questions about ONE account's data, which is given to you as a JSON snapshot with \
every message.

THE RULE THAT MATTERS MOST: you never produce a number that is not already in the snapshot.
- Quote figures exactly as they appear. Do not round them into something friendlier, do not \
convert currencies, do not annualise, do not compute ratios, averages, percentages, or \
totals that are not already computed for you.
- If a question needs a figure the snapshot does not contain, say plainly that it is not in \
the data you can see, and name which page or field would hold it. Never estimate. Never fall \
back on general market knowledge for a number about this account.
- If the snapshot and the question disagree about what exists, trust the snapshot.

WHAT THE DATA IS. Read the flags before answering:
- `bot_db.trades` are the trading daemon's own records. Rows flagged demo were generated by \
a seeding script — they are a simulation, NOT real money. Say so whenever you use them.
- `real_account_flex` is the real IBKR account statement (Flex). These are actual fills and \
actual NAV.
- `live_paper_account` is the paper-trading gateway, i.e. practice money.
Never blend the three into one figure, and always name which one you are quoting.

HOW TO ANSWER: brief and concrete — a sentence or two, or a short list. Lead with the number \
and what it is. No preamble, no "great question", no markdown headings. Answer in the same \
language the user wrote in; Hebrew questions get Hebrew answers, with numbers left in \
Western digits.

You are read-only. You cannot place, approve, close, or change anything, and you must not \
imply otherwise. Questions about what to trade next are outside what you can answer from an \
account snapshot: say that, rather than offering a view."""


class ChatTurn(BaseModel):
    role: str = Field(pattern="^(user|assistant)$")
    content: str = Field(min_length=1, max_length=8000)


class ChatBody(BaseModel):
    question: str = Field(min_length=1, max_length=2000)
    # Which console page the user is looking at, so the answer can favour what is on screen.
    page: str | None = Field(default=None, max_length=64)
    history: list[ChatTurn] = Field(default_factory=list)


def _f(v, digits: int = 2):
    """Round for display. Every number in the snapshot goes through here so the model is
    never handed 17 decimal places to truncate by itself."""
    try:
        return round(float(v), digits)
    except (TypeError, ValueError):
        return None


def _month(day: str) -> str:
    return day[:6] if day and len(day) >= 6 else ""


def build_snapshot(engine, flex_payload: dict | None, user_id: int,
                   is_owner: bool = True) -> dict:
    """Everything the model is allowed to know, computed here and nowhere else.

    Scoped to one account. The Flex half was already per-user; the daemon half reads tables
    that are now owner-stamped, and is filtered on the same user_id the API filters on — an
    assistant that could read across accounts would be a data leak wearing a friendly face.
    """

    def rows(sql: str, **p) -> list[dict]:
        with engine.connect() as c:
            return [dict(r) for r in c.execute(text(sql), p).mappings().all()]

    def one(sql: str, **p):
        with engine.connect() as c:
            return c.execute(text(sql), p).scalar()

    # No timestamp in here on purpose. This dict is sent as a cached prompt prefix, and a
    # clock reading would change the bytes on every request and silently defeat the cache —
    # the single most common way prompt caching is lost. The time of the request rides in
    # the user turn instead, after the cache breakpoint.
    snap: dict = {
        "note": "Every number here is computed by the server. Quote, do not recompute.",
    }

    # ---- the daemon's own database, this account's rows only -------------------------
    uid = user_id
    by_status = rows("SELECT status, is_demo, count(*) AS n FROM trades "
                     "WHERE user_id = :uid GROUP BY 1, 2", uid=uid)
    open_real = rows(
        "SELECT id, created_at, expiry, dte, vix_avg, entry_credit, quantity, "
        "put_short_strike, put_long_strike, call_short_strike, call_long_strike "
        "FROM trades WHERE user_id = :uid AND status = 'open' AND is_demo IS NOT TRUE "
        "ORDER BY created_at DESC", uid=uid)
    pnl = rows("SELECT COALESCE(SUM(p.realized), 0) AS total, count(*) AS closed "
               "FROM pnl p JOIN trades t ON t.id = p.trade_id WHERE t.user_id = :uid", uid=uid)
    recent = rows(
        "SELECT t.id, t.created_at::date AS date, t.status, t.is_demo, t.expiry, t.dte, "
        "t.vix_avg, t.entry_credit, t.quantity, p.realized "
        "FROM trades t LEFT JOIN pnl p ON p.trade_id = t.id "
        "WHERE t.user_id = :uid ORDER BY t.created_at DESC LIMIT 15", uid=uid)
    gates = rows(
        "SELECT accepted, reason, count(*) AS n FROM gate_decisions WHERE user_id = :uid "
        "GROUP BY 1, 2 ORDER BY n DESC LIMIT 12", uid=uid)
    control = rows("SELECT trading_enabled, updated_at, updated_by FROM control "
                   "WHERE user_id = :uid", uid=uid)

    snap["bot_db"] = {
        "what_this_is": "The trading daemon's durable log. Rows with demo=true are seeded "
                        "simulation, not real money.",
        "trade_counts": [{"status": r["status"], "demo": r["is_demo"], "n": r["n"]}
                         for r in by_status],
        "open_real_positions": [
            {**{k: (v.isoformat() if hasattr(v, "isoformat") else v)
                for k, v in r.items() if k != "created_at"},
             "opened": r["created_at"].date().isoformat() if r.get("created_at") else None}
            for r in open_real],
        "realized_pnl_all_rows": {"total": _f(pnl[0]["total"]) if pnl else None,
                                  "closed_trades": pnl[0]["closed"] if pnl else 0,
                                  "caveat": "Includes demo rows — see trade_counts."},
        "recent_trades": [
            {"id": r["id"], "date": str(r["date"]), "status": r["status"], "demo": r["is_demo"],
             "expiry": r["expiry"], "dte": r["dte"], "vix_at_entry": _f(r["vix_avg"]),
             "entry_credit": _f(r["entry_credit"]), "qty": r["quantity"],
             "realized": _f(r["realized"])}
            for r in recent],
        "gate_decisions_by_reason": [
            {"accepted": r["accepted"], "reason": r["reason"], "n": r["n"]} for r in gates],
        "pending_proposals": one("SELECT count(*) FROM trade_proposals "
                                 "WHERE user_id = :uid AND status = 'pending'", uid=uid),
        "trading_enabled": control[0]["trading_enabled"] if control else None,
    }

    # ---- live paper gateway (last recorded snapshot; no IB call on this path) -------
    # There is one broker connection and it belongs to the owner, so nobody else is told
    # anything about it — not even that it exists.
    nav = rows("SELECT ts, net_liq, daily_pnl, unrealized FROM nav_snapshots "
               "WHERE user_id = :uid ORDER BY ts DESC LIMIT 1", uid=uid) if is_owner else []
    snap["live_paper_account"] = {
        "what_this_is": "IBKR paper (practice) account, last recorded snapshot.",
        "as_of": nav[0]["ts"].isoformat() if nav else None,
        "net_liq": _f(nav[0]["net_liq"]) if nav else None,
        "daily_pnl": _f(nav[0]["daily_pnl"]) if nav else None,
        "unrealized": _f(nav[0]["unrealized"]) if nav else None,
    } if nav else {"what_this_is": "IBKR paper account", "available": False,
                   "why": "This account has no broker connection in this console."}

    # ---- the real account, from the cached Flex statement ---------------------------
    if not (flex_payload and flex_payload.get("ok")):
        snap["real_account_flex"] = {
            "available": False,
            "why": "No cached IBKR Flex statement. Open the Performance page to fetch one, "
                   "or add a Flex token and query ID in Settings.",
        }
        return snap

    trades = flex_payload.get("trades") or []
    nav_days = flex_payload.get("navDays") or []

    per_underlying: dict[str, dict] = defaultdict(lambda: {"n": 0, "realized": 0.0,
                                                           "commission": 0.0})
    per_month: dict[str, dict] = defaultdict(lambda: {"n": 0, "realized": 0.0,
                                                      "commission": 0.0})
    realized_total = commission_total = 0.0
    for t in trades:
        u = t.get("underlying") or t.get("symbol") or "?"
        m = _month(t.get("date") or "")
        r = float(t.get("realized") or 0.0)
        c = float(t.get("commission") or 0.0)
        realized_total += r
        commission_total += c
        per_underlying[u]["n"] += 1
        per_underlying[u]["realized"] += r
        per_underlying[u]["commission"] += c
        if m:
            per_month[m]["n"] += 1
            per_month[m]["realized"] += r
            per_month[m]["commission"] += c

    top = sorted(per_underlying.items(), key=lambda kv: kv[1]["n"], reverse=True)[:15]
    months = sorted(per_month.items())

    curve = None
    if nav_days:
        lo = min(nav_days, key=lambda d: d["end"])
        hi = max(nav_days, key=lambda d: d["end"])
        curve = {
            "days": len(nav_days),
            "first": {"date": nav_days[0]["date"], "nav": _f(nav_days[0]["end"])},
            "last": {"date": nav_days[-1]["date"], "nav": _f(nav_days[-1]["end"])},
            "lowest": {"date": lo["date"], "nav": _f(lo["end"])},
            "highest": {"date": hi["date"], "nav": _f(hi["end"])},
        }

    snap["real_account_flex"] = {
        "what_this_is": "REAL IBKR account statement (Flex). Actual fills and actual NAV.",
        "available": True,
        "account": flex_payload.get("account"),
        "period": {"from": flex_payload.get("from"), "to": flex_payload.get("to")},
        "nav_summary": {k: _f(v) for k, v in (flex_payload.get("nav") or {}).items()},
        "nav_curve": curve,
        "trade_count": len(trades),
        "realized_total_all_trades": _f(realized_total),
        "commission_total_all_trades": _f(commission_total),
        "by_underlying_top15": [
            {"underlying": u, "fills": v["n"], "realized": _f(v["realized"]),
             "commission": _f(v["commission"])} for u, v in top],
        "by_month": [
            {"month": m, "fills": v["n"], "realized": _f(v["realized"]),
             "commission": _f(v["commission"])} for m, v in months],
        "most_recent_fills": [
            {"date": t.get("date"), "symbol": t.get("symbol"),
             "underlying": t.get("underlying"), "asset": t.get("assetCategory"),
             "putCall": t.get("putCall"), "strike": t.get("strike"), "expiry": t.get("expiry"),
             "side": t.get("buySell"), "qty": t.get("quantity"), "price": t.get("price"),
             "proceeds": t.get("proceeds"), "commission": t.get("commission"),
             "realized": t.get("realized")}
            for t in trades[-20:]],
        "caveat": "by_underlying/by_month/realized totals are summed by the server from the "
                  "full statement; per-fill rows above are only the most recent 20.",
    }
    return snap


def build_router(engine, user_id_dep, creds_dep, flex_cache_read, is_owner):
    router = APIRouter(prefix="/chat", tags=["chat"])

    def _key() -> str | None:
        return os.getenv("ANTHROPIC_API_KEY") or None

    @router.get("/status")
    def status(_: int = Depends(user_id_dep)) -> dict:
        return {"configured": bool(_key()), "model": MODEL,
                "workspace_set": bool(WORKSPACE_ID)}

    @router.post("")
    def ask(body: ChatBody, uid: int = Depends(user_id_dep),
            creds: dict = Depends(creds_dep)) -> dict:
        key = _key()
        if not key:
            return {
                "configured": False,
                "answer": None,
                "error": "No ANTHROPIC_API_KEY is set. Add one to .env and restart the api "
                         "service to enable the assistant.",
            }
        try:
            import anthropic
        except ImportError:
            raise HTTPException(500, "the anthropic package is not installed in this image")

        cached = flex_cache_read(uid)
        snapshot = build_snapshot(engine, cached[1] if cached else None, uid,
                                  is_owner=is_owner(uid))

        import json
        # Render order is system -> messages, so the stable half (instructions + snapshot)
        # goes in system behind one cache breakpoint, and everything that varies per
        # question (the clock, the page, the history, the question) comes after it. Follow-up
        # questions in a session then re-read ~6k tokens at cache rates instead of full price.
        prefix = [
            {"type": "text", "text": SYSTEM},
            {"type": "text",
             "text": f"<snapshot>\n{json.dumps(snapshot, default=str)}\n</snapshot>",
             "cache_control": {"type": "ephemeral"}},
        ]
        now = datetime.now(timezone.utc).isoformat(timespec="seconds")
        messages: list[dict] = []
        for turn in body.history[-MAX_HISTORY:]:
            messages.append({"role": turn.role, "content": turn.content})
        messages.append({"role": "user", "content":
                         f"<request_time>{now}</request_time>\n"
                         f"<console_page>{body.page or 'unknown'}</console_page>\n\n"
                         f"{body.question}"})

        client = anthropic.Anthropic(
            api_key=key,
            default_headers={"anthropic-workspace-id": WORKSPACE_ID} if WORKSPACE_ID else None,
        )
        try:
            resp = client.messages.create(
                model=MODEL,
                max_tokens=MAX_TOKENS,
                output_config={"effort": EFFORT},
                system=prefix,
                messages=messages,
            )
        except anthropic.AuthenticationError:
            return {"configured": True, "answer": None,
                    "error": "The Anthropic API key was rejected."}
        except anthropic.RateLimitError:
            return {"configured": True, "answer": None,
                    "error": "Rate limited by the Anthropic API — try again shortly."}
        except anthropic.APIStatusError as e:
            log.warning("chat API error %s: %s", e.status_code, e.message)
            # Workspace problems are worth naming: the fix is a config value, not a retry.
            # Distinguish the two — "unset" and "wrong" need different actions, and lumping
            # them together sent us chasing a setting that was already in place.
            msg = (e.message or "")
            if "anthropic-workspace-id is required" in msg:
                return {"configured": True, "answer": None,
                        "error": "This API key is identity-linked and needs a workspace. Set "
                                 "ANTHROPIC_WORKSPACE_ID in .env and restart the api service."}
            if "workspace" in msg.lower():
                return {"configured": True, "answer": None,
                        "error": f"The API rejected the configured workspace: {msg}"}
            return {"configured": True, "answer": None,
                    "error": f"The model call failed ({e.status_code})."}
        except anthropic.APIConnectionError:
            return {"configured": True, "answer": None,
                    "error": "Could not reach the Anthropic API from this container."}

        if resp.stop_reason == "refusal":
            return {"configured": True, "answer": None,
                    "error": "The model declined to answer that."}
        answer = "".join(b.text for b in resp.content if b.type == "text").strip()
        if not answer and resp.stop_reason == "max_tokens":
            # Thinking tokens count against max_tokens, so a hard question can burn the whole
            # budget before any prose is emitted. Say that, rather than showing a blank turn.
            return {"configured": True, "answer": None,
                    "error": "The answer did not fit in the token budget. Ask something "
                             "narrower, or raise CHAT_MAX_TOKENS."}
        log.info("chat answered", extra={"user_id": uid})
        return {
            "configured": True,
            "answer": answer or None,
            "model": resp.model,
            "usage": {"input": resp.usage.input_tokens,
                      "output": resp.usage.output_tokens,
                      # Zero cache_read across repeated questions means the prefix stopped
                      # being byte-stable — worth being able to see from the outside.
                      "cache_read": getattr(resp.usage, "cache_read_input_tokens", None),
                      "cache_write": getattr(resp.usage, "cache_creation_input_tokens", None)},
        }

    return router
