"""Grounded Q&A over the data the console already shows.

The rule this module exists to enforce: **the model never produces a number.** Every figure
it can mention is computed here, in deterministic Python, from Postgres and the cached Flex
statement, and handed to Claude as a read-only snapshot. Claude's job is to find the right
number in that snapshot and explain it — not to calculate, estimate, or recall one.

That is why the snapshot is aggregated server-side (top underlyings, per-month totals, a
handful of recent rows) rather than shipping 3,000 raw trades and hoping the model adds them
up correctly. If a question needs a figure the snapshot does not contain, the correct answer
is "that isn't in the data I can see" — the system prompt says so explicitly, and the UI
tells the user the same thing.

Unconfigured (no ANTHROPIC_API_KEY) is a normal state, not an error: the endpoint reports
configured=false and the widget explains what to add.
"""
from __future__ import annotations

import json
import logging
import os
from collections import defaultdict
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field
from sqlalchemy import text

log = logging.getLogger("chat")

MODEL = os.getenv("CHAT_MODEL", "claude-opus-5")
# An identity-linked API key must say which workspace it is acting in; a plain key ignores
# this. Sent as a default header so every call carries it.
WORKSPACE_ID = os.getenv("ANTHROPIC_WORKSPACE_ID") or None
MAX_TOKENS = int(os.getenv("CHAT_MAX_TOKENS", "6000"))
# How much history the widget may replay. Long chats mostly re-ask the same snapshot, so a
# short window keeps cost predictable without hurting follow-up questions.
MAX_HISTORY = 10
# Looking a figure up in a JSON blob is not a reasoning problem. Measured against the two
# questions that matter (keeping real apart from demo; refusing to invent), low effort gave
# the same answers as the default in half the wall time — and because ~6k snapshot tokens
# dominate the bill, effort buys latency here far more than it buys money.
EFFORT = os.getenv("CHAT_EFFORT", "low")

SYSTEM = """You are the analyst built into a private SPX iron-condor trading console. You \
answer questions about ONE account's data. You are given a JSON overview snapshot with every \
message, and tools that read that account's COMPLETE IBKR Flex statement — every fill and \
every NAV day, not a sample.

THE RULE THAT MATTERS MOST: you never produce a number yourself. Every figure you state must \
come back verbatim from the snapshot or from a tool result.
- Quote figures exactly as they come. Do not round them into something friendlier, do not \
convert currencies, do not annualise, and do not compute ratios, averages, percentages, \
differences or totals in your head.
- Never add rows up yourself. If you find yourself about to sum, count, rank, or compare \
across fills, that is a signal to call `aggregate_fills` or `search_fills` instead — they \
compute over every matching row on the server and return the total to you. A tool call is \
always better than arithmetic.
- `search_fills` returns `matched` (how many rows matched) and `totals` (computed over ALL \
of them) alongside a sample of rows. Quote `matched` and `totals`; never count the sample \
rows and present that as the answer.
- If something genuinely is not derivable from the snapshot or the tools, say so plainly and \
name what would be needed. Never estimate, and never fall back on general market knowledge \
for a number about this account.
- If the data and the question disagree about what exists, trust the data.

USING THE TOOLS: reach for them for anything more specific than the overview — a symbol, a \
date range, a month, an expiry, "how many", "which was biggest", "what did I do on X". \
Chain them when a question needs it (aggregate to find the month, then search to see the \
fills in it). Say which filter you used, so the user can check you. If a tool returns zero \
matches, report that as the answer rather than trying another interpretation silently.

WHAT THE DATA IS. Read the flags before answering:
- `bot_db.trades` are the trading daemon's own records. Rows flagged demo were generated by \
a seeding script — they are a simulation, NOT real money. Say so whenever you use them.
- `real_account_flex` is the real IBKR account statement (Flex). These are actual fills and \
actual NAV.
- `live_paper_account` is the paper-trading gateway, i.e. practice money.
Never blend the three into one figure, and always name which one you are quoting.

HOW TO ANSWER: brief and concrete — a sentence or two, or a short list. Lead with the number \
and what it is. No preamble, no "great question", no markdown headings. Answer in the same \
language the user wrote in; Hebrew questions get Hebrew answers, with numbers left in \
Western digits.

PRECISION: state the figure and what it is, and name which source it came from (the real \
Flex statement, the daemon's log, or the paper account). When a number is a server-computed \
total over a filter, say what the filter was. Never present a partial sample as a complete \
answer.

You are read-only. You cannot place, approve, close, or change anything, and you must not \
imply otherwise. Questions about what to trade next are outside what you can answer from an \
account snapshot: say that, rather than offering a view."""


class ChatTurn(BaseModel):
    role: str = Field(pattern="^(user|assistant)$")
    content: str = Field(min_length=1, max_length=8000)


class ChatBody(BaseModel):
    question: str = Field(min_length=1, max_length=2000)
    # Which console page the user is looking at, so the answer can favour what is on screen.
    page: str | None = Field(default=None, max_length=64)
    history: list[ChatTurn] = Field(default_factory=list)


def _f(v, digits: int = 2):
    """Round for display. Every number in the snapshot goes through here so the model is
    never handed 17 decimal places to truncate by itself."""
    try:
        return round(float(v), digits)
    except (TypeError, ValueError):
        return None


def _month(day: str) -> str:
    return day[:6] if day and len(day) >= 6 else ""


def build_snapshot(engine, flex_payload: dict | None, user_id: int,
                   is_owner: bool = True) -> dict:
    """Everything the model is allowed to know, computed here and nowhere else.

    Scoped to one account. The Flex half was already per-user; the daemon half reads tables
    that are now owner-stamped, and is filtered on the same user_id the API filters on — an
    assistant that could read across accounts would be a data leak wearing a friendly face.
    """

    def rows(sql: str, **p) -> list[dict]:
        with engine.connect() as c:
            return [dict(r) for r in c.execute(text(sql), p).mappings().all()]

    def one(sql: str, **p):
        with engine.connect() as c:
            return c.execute(text(sql), p).scalar()

    # No timestamp in here on purpose. This dict is sent as a cached prompt prefix, and a
    # clock reading would change the bytes on every request and silently defeat the cache —
    # the single most common way prompt caching is lost. The time of the request rides in
    # the user turn instead, after the cache breakpoint.
    snap: dict = {
        "note": "Every number here is computed by the server. Quote, do not recompute.",
    }

    # ---- the daemon's own database, this account's rows only -------------------------
    uid = user_id
    by_status = rows("SELECT status, is_demo, count(*) AS n FROM trades "
                     "WHERE user_id = :uid GROUP BY 1, 2", uid=uid)
    open_real = rows(
        "SELECT id, created_at, expiry, dte, vix_avg, entry_credit, quantity, "
        "put_short_strike, put_long_strike, call_short_strike, call_long_strike "
        "FROM trades WHERE user_id = :uid AND status = 'open' AND is_demo IS NOT TRUE "
        "ORDER BY created_at DESC", uid=uid)
    pnl = rows("SELECT COALESCE(SUM(p.realized), 0) AS total, count(*) AS closed "
               "FROM pnl p JOIN trades t ON t.id = p.trade_id WHERE t.user_id = :uid", uid=uid)
    recent = rows(
        "SELECT t.id, t.created_at::date AS date, t.status, t.is_demo, t.expiry, t.dte, "
        "t.vix_avg, t.entry_credit, t.quantity, p.realized "
        "FROM trades t LEFT JOIN pnl p ON p.trade_id = t.id "
        "WHERE t.user_id = :uid ORDER BY t.created_at DESC LIMIT 15", uid=uid)
    gates = rows(
        "SELECT accepted, reason, count(*) AS n FROM gate_decisions WHERE user_id = :uid "
        "GROUP BY 1, 2 ORDER BY n DESC LIMIT 12", uid=uid)
    control = rows("SELECT trading_enabled, updated_at, updated_by FROM control "
                   "WHERE user_id = :uid", uid=uid)

    snap["bot_db"] = {
        "what_this_is": "The trading daemon's durable log. Rows with demo=true are seeded "
                        "simulation, not real money.",
        "trade_counts": [{"status": r["status"], "demo": r["is_demo"], "n": r["n"]}
                         for r in by_status],
        "open_real_positions": [
            {**{k: (v.isoformat() if hasattr(v, "isoformat") else v)
                for k, v in r.items() if k != "created_at"},
             "opened": r["created_at"].date().isoformat() if r.get("created_at") else None}
            for r in open_real],
        "realized_pnl_all_rows": {"total": _f(pnl[0]["total"]) if pnl else None,
                                  "closed_trades": pnl[0]["closed"] if pnl else 0,
                                  "caveat": "Includes demo rows — see trade_counts."},
        "recent_trades": [
            {"id": r["id"], "date": str(r["date"]), "status": r["status"], "demo": r["is_demo"],
             "expiry": r["expiry"], "dte": r["dte"], "vix_at_entry": _f(r["vix_avg"]),
             "entry_credit": _f(r["entry_credit"]), "qty": r["quantity"],
             "realized": _f(r["realized"])}
            for r in recent],
        "gate_decisions_by_reason": [
            {"accepted": r["accepted"], "reason": r["reason"], "n": r["n"]} for r in gates],
        "pending_proposals": one("SELECT count(*) FROM trade_proposals "
                                 "WHERE user_id = :uid AND status = 'pending'", uid=uid),
        "trading_enabled": control[0]["trading_enabled"] if control else None,
    }

    # ---- live paper gateway (last recorded snapshot; no IB call on this path) -------
    # There is one broker connection and it belongs to the owner, so nobody else is told
    # anything about it — not even that it exists.
    nav = rows("SELECT ts, net_liq, daily_pnl, unrealized FROM nav_snapshots "
               "WHERE user_id = :uid ORDER BY ts DESC LIMIT 1", uid=uid) if is_owner else []
    snap["live_paper_account"] = {
        "what_this_is": "IBKR paper (practice) account, last recorded snapshot.",
        "as_of": nav[0]["ts"].isoformat() if nav else None,
        "net_liq": _f(nav[0]["net_liq"]) if nav else None,
        "daily_pnl": _f(nav[0]["daily_pnl"]) if nav else None,
        "unrealized": _f(nav[0]["unrealized"]) if nav else None,
    } if nav else {"what_this_is": "IBKR paper account", "available": False,
                   "why": "This account has no broker connection in this console."}

    # ---- the real account, from the cached Flex statement ---------------------------
    if not (flex_payload and flex_payload.get("ok")):
        snap["real_account_flex"] = {
            "available": False,
            "why": "No cached IBKR Flex statement. Open the Performance page to fetch one, "
                   "or add a Flex token and query ID in Settings.",
        }
        return snap

    trades = flex_payload.get("trades") or []
    nav_days = flex_payload.get("navDays") or []

    per_underlying: dict[str, dict] = defaultdict(lambda: {"n": 0, "realized": 0.0,
                                                           "commission": 0.0})
    per_month: dict[str, dict] = defaultdict(lambda: {"n": 0, "realized": 0.0,
                                                      "commission": 0.0})
    realized_total = commission_total = 0.0
    for t in trades:
        u = t.get("underlying") or t.get("symbol") or "?"
        m = _month(t.get("date") or "")
        r = float(t.get("realized") or 0.0)
        c = float(t.get("commission") or 0.0)
        realized_total += r
        commission_total += c
        per_underlying[u]["n"] += 1
        per_underlying[u]["realized"] += r
        per_underlying[u]["commission"] += c
        if m:
            per_month[m]["n"] += 1
            per_month[m]["realized"] += r
            per_month[m]["commission"] += c

    top = sorted(per_underlying.items(), key=lambda kv: kv[1]["n"], reverse=True)[:15]
    months = sorted(per_month.items())

    curve = None
    if nav_days:
        lo = min(nav_days, key=lambda d: d["end"])
        hi = max(nav_days, key=lambda d: d["end"])
        curve = {
            "days": len(nav_days),
            "first": {"date": nav_days[0]["date"], "nav": _f(nav_days[0]["end"])},
            "last": {"date": nav_days[-1]["date"], "nav": _f(nav_days[-1]["end"])},
            "lowest": {"date": lo["date"], "nav": _f(lo["end"])},
            "highest": {"date": hi["date"], "nav": _f(hi["end"])},
        }

    snap["real_account_flex"] = {
        "what_this_is": "REAL IBKR account statement (Flex). Actual fills and actual NAV.",
        "available": True,
        "account": flex_payload.get("account"),
        "period": {"from": flex_payload.get("from"), "to": flex_payload.get("to")},
        "nav_summary": {k: _f(v) for k, v in (flex_payload.get("nav") or {}).items()},
        "nav_curve": curve,
        "trade_count": len(trades),
        "realized_total_all_trades": _f(realized_total),
        "commission_total_all_trades": _f(commission_total),
        "by_underlying_top15": [
            {"underlying": u, "fills": v["n"], "realized": _f(v["realized"]),
             "commission": _f(v["commission"])} for u, v in top],
        "by_month": [
            {"month": m, "fills": v["n"], "realized": _f(v["realized"]),
             "commission": _f(v["commission"])} for m, v in months],
        "most_recent_fills": [
            {"date": t.get("date"), "symbol": t.get("symbol"),
             "underlying": t.get("underlying"), "asset": t.get("assetCategory"),
             "putCall": t.get("putCall"), "strike": t.get("strike"), "expiry": t.get("expiry"),
             "side": t.get("buySell"), "qty": t.get("quantity"), "price": t.get("price"),
             "proceeds": t.get("proceeds"), "commission": t.get("commission"),
             "realized": t.get("realized")}
            for t in trades[-20:]],
        "caveat": "by_underlying/by_month/realized totals are summed by the server from the "
                  "full statement; per-fill rows above are only the most recent 20.",
    }
    return snap


# --------------------------------------------------------------- tools ------
# Every one of these runs over the *complete* cached statement — all 3,000-odd fills, all
# 261 NAV days — and returns numbers this file computed. That is the point: the model gets
# the whole file without ever being handed 3,000 rows to add up, which is precisely where a
# language model would produce a confident wrong total.

MAX_ROWS = 60          # sample rows returned; totals always cover the full match
MAX_TOOL_TURNS = 6     # bounded so a confused model cannot loop up a bill

TOOLS = [
    {
        "name": "search_fills",
        "description": (
            "Search this account's COMPLETE IBKR Flex statement — every executed fill, not a "
            "sample. Returns `matched` (how many fills matched the filter), `totals` computed "
            "by the server over ALL of them, and up to `limit` example rows. Use for questions "
            "about particular symbols, dates, expiries, option legs or individual trades. "
            "Quote `matched` and `totals`; never count the sample rows yourself."),
        "input_schema": {
            "type": "object",
            "properties": {
                "underlying": {"type": "string",
                               "description": "Exact underlying, e.g. SPX, SPY, AAPL."},
                "symbol_contains": {"type": "string",
                                    "description": "Substring of the full contract symbol."},
                "date_from": {"type": "string", "description": "YYYYMMDD, inclusive."},
                "date_to": {"type": "string", "description": "YYYYMMDD, inclusive."},
                "expiry": {"type": "string", "description": "Option expiry, YYYYMMDD."},
                "put_call": {"type": "string", "enum": ["P", "C"]},
                "side": {"type": "string", "enum": ["BUY", "SELL"]},
                "open_close": {"type": "string", "enum": ["O", "C"],
                               "description": "O = opening, C = closing."},
                "asset_category": {"type": "string",
                                   "description": "e.g. OPT, STK, CASH."},
                "sort": {"type": "string",
                         "enum": ["date_desc", "date_asc", "realized_desc", "realized_asc",
                                  "abs_realized_desc"],
                         "description": "Order of the sample rows. Default date_desc."},
                "limit": {"type": "integer",
                          "description": f"Sample rows to return, 1-{MAX_ROWS}. Default 20."},
            },
            "additionalProperties": False,
        },
    },
    {
        "name": "aggregate_fills",
        "description": (
            "Group the COMPLETE Flex statement and return server-computed sums per group. Use "
            "this for every 'how much', 'how many', 'which is biggest/worst', 'per month', "
            "'per symbol' question. It applies the same filters as search_fills first."),
        "input_schema": {
            "type": "object",
            "properties": {
                "group_by": {"type": "string",
                             "enum": ["underlying", "symbol", "month", "day", "expiry",
                                      "put_call", "asset_category", "side", "open_close"],
                             "description": "Required. What to group by."},
                "underlying": {"type": "string"},
                "date_from": {"type": "string", "description": "YYYYMMDD, inclusive."},
                "date_to": {"type": "string", "description": "YYYYMMDD, inclusive."},
                "expiry": {"type": "string"},
                "put_call": {"type": "string", "enum": ["P", "C"]},
                "side": {"type": "string", "enum": ["BUY", "SELL"]},
                "open_close": {"type": "string", "enum": ["O", "C"]},
                "asset_category": {"type": "string"},
                "sort_by": {"type": "string",
                            "enum": ["fills", "realized", "commission", "proceeds", "key"],
                            "description": "Default fills."},
                "ascending": {"type": "boolean", "description": "Default false."},
                "limit": {"type": "integer", "description": "Groups to return. Default 25."},
            },
            "required": ["group_by"],
            "additionalProperties": False,
        },
    },
    {
        "name": "nav_history",
        "description": (
            "Daily NAV rows from the COMPLETE statement, with server-computed first, last, "
            "highest, lowest and change over the range. Use for questions about account value "
            "over time, drawdowns, or a specific period."),
        "input_schema": {
            "type": "object",
            "properties": {
                "date_from": {"type": "string", "description": "YYYYMMDD, inclusive."},
                "date_to": {"type": "string", "description": "YYYYMMDD, inclusive."},
                "limit": {"type": "integer",
                          "description": f"Rows to return, 1-{MAX_ROWS}. Default 30. Totals "
                                         "always cover the whole range."},
            },
            "additionalProperties": False,
        },
    },
]

_GROUP_KEY = {
    "underlying": lambda t: t.get("underlying") or t.get("symbol") or "?",
    "symbol": lambda t: t.get("symbol") or "?",
    "month": lambda t: (t.get("date") or "")[:6] or "?",
    "day": lambda t: t.get("date") or "?",
    "expiry": lambda t: t.get("expiry") or "?",
    "put_call": lambda t: t.get("putCall") or "?",
    "asset_category": lambda t: t.get("assetCategory") or "?",
    "side": lambda t: t.get("buySell") or "?",
    "open_close": lambda t: t.get("openClose") or "?",
}


def _matches(t: dict, a: dict) -> bool:
    def eq(field, key, upper=True):
        want = a.get(key)
        if want in (None, ""):
            return True
        got = str(t.get(field) or "")
        return got.upper() == str(want).upper() if upper else got == want

    date = t.get("date") or ""
    if a.get("date_from") and date < str(a["date_from"]):
        return False
    if a.get("date_to") and date > str(a["date_to"]):
        return False
    if a.get("symbol_contains") and str(a["symbol_contains"]).upper() not in \
            str(t.get("symbol") or "").upper():
        return False
    return all([eq("underlying", "underlying"), eq("expiry", "expiry"),
                eq("putCall", "put_call"), eq("buySell", "side"),
                eq("openClose", "open_close"), eq("assetCategory", "asset_category")])


def _totals(rows: list[dict]) -> dict:
    return {
        "fills": len(rows),
        "realized": _f(sum(float(t.get("realized") or 0.0) for t in rows)),
        "commission": _f(sum(float(t.get("commission") or 0.0) for t in rows)),
        "proceeds": _f(sum(float(t.get("proceeds") or 0.0) for t in rows)),
        "quantity": _f(sum(float(t.get("quantity") or 0.0) for t in rows)),
    }


def _slim(t: dict) -> dict:
    return {k: t.get(k) for k in ("date", "symbol", "underlying", "assetCategory", "putCall",
                                 "strike", "expiry", "buySell", "quantity", "price",
                                 "proceeds", "commission", "realized", "openClose")}


def run_tool(name: str, args: dict, flex_payload: dict | None) -> dict:
    """Execute one tool. Returns a plain dict; never raises into the model loop."""
    if not (flex_payload and flex_payload.get("ok")):
        return {"error": "No cached IBKR Flex statement for this account, so the full "
                         "statement cannot be searched. Open the Performance page to fetch "
                         "one, or add a Flex token and query ID in Settings."}
    args = args or {}
    try:
        limit = int(args.get("limit") or (20 if name == "search_fills" else 30))
    except (TypeError, ValueError):
        limit = 20
    limit = max(1, min(limit, MAX_ROWS))

    if name == "nav_history":
        days = [d for d in (flex_payload.get("navDays") or [])
                if (not args.get("date_from") or d["date"] >= str(args["date_from"]))
                and (not args.get("date_to") or d["date"] <= str(args["date_to"]))]
        if not days:
            return {"days": 0, "rows": [], "note": "No NAV days in that range."}
        lo = min(days, key=lambda d: d["end"])
        hi = max(days, key=lambda d: d["end"])
        return {
            "days": len(days),
            "first": {"date": days[0]["date"], "nav": _f(days[0]["end"])},
            "last": {"date": days[-1]["date"], "nav": _f(days[-1]["end"])},
            "lowest": {"date": lo["date"], "nav": _f(lo["end"])},
            "highest": {"date": hi["date"], "nav": _f(hi["end"])},
            "change_over_range": _f(days[-1]["end"] - days[0]["start"]),
            "deposits_over_range": _f(sum(d.get("deposits") or 0.0 for d in days)),
            "rows_note": f"{len(days)} days matched; showing up to {limit}.",
            "rows": [{"date": d["date"], "start": _f(d["start"]), "end": _f(d["end"]),
                      "deposits": _f(d.get("deposits")), "mtm": _f(d.get("mtm")),
                      "commissions": _f(d.get("commissions"))} for d in days[-limit:]],
        }

    hits = [t for t in (flex_payload.get("trades") or []) if _matches(t, args)]

    if name == "aggregate_fills":
        keyer = _GROUP_KEY.get(args.get("group_by") or "underlying")
        if keyer is None:
            return {"error": f"unknown group_by {args.get('group_by')!r}"}
        buckets: dict = defaultdict(list)
        for t in hits:
            buckets[keyer(t)].append(t)
        groups = [{"key": k, **_totals(v)} for k, v in buckets.items()]
        sort_by = args.get("sort_by") or "fills"
        asc = bool(args.get("ascending"))
        groups.sort(key=(lambda g: g["key"]) if sort_by == "key"
                    else (lambda g: (g.get(sort_by) or 0)), reverse=not asc)
        return {
            "filter_applied": {k: v for k, v in args.items()
                               if k not in ("group_by", "sort_by", "ascending", "limit")},
            "matched_fills": len(hits),
            "totals_over_all_matches": _totals(hits),
            "group_by": args.get("group_by"),
            "groups_found": len(groups),
            "groups": groups[:max(1, min(int(args.get("limit") or 25), 200))],
        }

    order = args.get("sort") or "date_desc"
    keyfn = {
        "date_desc": (lambda t: t.get("dateTime") or "", True),
        "date_asc": (lambda t: t.get("dateTime") or "", False),
        "realized_desc": (lambda t: float(t.get("realized") or 0.0), True),
        "realized_asc": (lambda t: float(t.get("realized") or 0.0), False),
        "abs_realized_desc": (lambda t: abs(float(t.get("realized") or 0.0)), True),
    }.get(order, (lambda t: t.get("dateTime") or "", True))
    rows = sorted(hits, key=keyfn[0], reverse=keyfn[1])[:limit]
    return {
        "filter_applied": {k: v for k, v in args.items() if k not in ("sort", "limit")},
        "matched": len(hits),
        "totals": _totals(hits),
        "totals_cover": "all matched fills, not just the rows below",
        "rows_returned": len(rows),
        "rows": [_slim(t) for t in rows],
    }


def build_router(engine, user_id_dep, creds_dep, flex_cache_read, is_owner):
    router = APIRouter(prefix="/chat", tags=["chat"])

    def _key() -> str | None:
        return os.getenv("ANTHROPIC_API_KEY") or None

    @router.get("/status")
    def status(_: int = Depends(user_id_dep)) -> dict:
        return {"configured": bool(_key()), "model": MODEL,
                "workspace_set": bool(WORKSPACE_ID)}

    @router.post("")
    def ask(body: ChatBody, uid: int = Depends(user_id_dep),
            creds: dict = Depends(creds_dep)) -> dict:
        key = _key()
        if not key:
            return {
                "configured": False,
                "answer": None,
                "error": "No ANTHROPIC_API_KEY is set. Add one to .env and restart the api "
                         "service to enable the assistant.",
            }
        try:
            import anthropic
        except ImportError:
            raise HTTPException(500, "the anthropic package is not installed in this image")

        cached = flex_cache_read(uid)
        snapshot = build_snapshot(engine, cached[1] if cached else None, uid,
                                  is_owner=is_owner(uid))

        # Render order is system -> messages, so the stable half (instructions + snapshot)
        # goes in system behind one cache breakpoint, and everything that varies per
        # question (the clock, the page, the history, the question) comes after it. Follow-up
        # questions in a session then re-read ~6k tokens at cache rates instead of full price.
        prefix = [
            {"type": "text", "text": SYSTEM},
            {"type": "text",
             "text": f"<snapshot>\n{json.dumps(snapshot, default=str)}\n</snapshot>",
             "cache_control": {"type": "ephemeral"}},
        ]
        now = datetime.now(timezone.utc).isoformat(timespec="seconds")
        messages: list[dict] = []
        for turn in body.history[-MAX_HISTORY:]:
            messages.append({"role": turn.role, "content": turn.content})
        messages.append({"role": "user", "content":
                         f"<request_time>{now}</request_time>\n"
                         f"<console_page>{body.page or 'unknown'}</console_page>\n\n"
                         f"{body.question}"})

        client = anthropic.Anthropic(
            api_key=key,
            default_headers={"anthropic-workspace-id": WORKSPACE_ID} if WORKSPACE_ID else None,
        )

        def fail(err: str) -> dict:
            return {"configured": True, "answer": None, "error": err}

        # The tool loop. Bounded at MAX_TOOL_TURNS: the model may look things up several
        # times (aggregate to find a month, then search inside it) but cannot spin.
        flex_payload = cached[1] if cached else None
        used: list[dict] = []
        totals = {"input": 0, "output": 0, "cache_read": 0, "cache_write": 0}
        resp = None
        for _turn in range(MAX_TOOL_TURNS):
            try:
                resp = client.messages.create(
                    model=MODEL,
                    max_tokens=MAX_TOKENS,
                    output_config={"effort": EFFORT},
                    system=prefix,
                    tools=TOOLS,
                    messages=messages,
                )
            except anthropic.AuthenticationError:
                return fail("The Anthropic API key was rejected.")
            except anthropic.RateLimitError:
                return fail("Rate limited by the Anthropic API — try again shortly.")
            except anthropic.APIStatusError as e:
                log.warning("chat API error %s: %s", e.status_code, e.message)
                # Workspace problems are worth naming: the fix is a config value, not a
                # retry. "unset" and "wrong" need different actions, and lumping them
                # together sent us chasing a setting that was already in place.
                msg = (e.message or "")
                if "anthropic-workspace-id is required" in msg:
                    return fail("This API key is identity-linked and needs a workspace. Set "
                                "ANTHROPIC_WORKSPACE_ID in .env and restart the api service.")
                if "workspace" in msg.lower():
                    return fail(f"The API rejected the configured workspace: {msg}")
                return fail(f"The model call failed ({e.status_code}).")
            except anthropic.APIConnectionError:
                return fail("Could not reach the Anthropic API from this container.")

            u = resp.usage
            totals["input"] += u.input_tokens
            totals["output"] += u.output_tokens
            totals["cache_read"] += getattr(u, "cache_read_input_tokens", 0) or 0
            totals["cache_write"] += getattr(u, "cache_creation_input_tokens", 0) or 0

            if resp.stop_reason == "refusal":
                return fail("The model declined to answer that.")
            if resp.stop_reason != "tool_use":
                break

            # Execute every requested call, then return all results in ONE user message —
            # splitting them teaches the model to stop asking for parallel lookups.
            calls = [b for b in resp.content if b.type == "tool_use"]
            results = []
            for call in calls:
                try:
                    out = run_tool(call.name, dict(call.input or {}), flex_payload)
                except Exception as e:                   # noqa: BLE001 - never break the loop
                    log.warning("tool %s failed: %s", call.name, e)
                    out = {"error": f"{type(e).__name__}: {e}"}
                used.append({"tool": call.name, "input": call.input})
                results.append({"type": "tool_result", "tool_use_id": call.id,
                                "content": json.dumps(out, default=str),
                                "is_error": bool(out.get("error"))})
            messages.append({"role": "assistant", "content": resp.content})
            messages.append({"role": "user", "content": results})
        else:
            return fail("The assistant kept looking things up without reaching an answer. "
                        "Try a narrower question.")

        answer = "".join(b.text for b in resp.content if b.type == "text").strip()
        if not answer and resp.stop_reason == "max_tokens":
            # Thinking tokens count against max_tokens, so a hard question can burn the whole
            # budget before any prose is emitted. Say that, rather than showing a blank turn.
            return fail("The answer did not fit in the token budget. Ask something narrower, "
                        "or raise CHAT_MAX_TOKENS.")
        log.info("chat answered", extra={"user_id": uid, "tool_calls": len(used)})
        return {
            "configured": True,
            "answer": answer or None,
            "model": resp.model,
            # What it actually looked at, so an answer can be checked rather than trusted.
            "tools_used": used,
            # Zero cache_read across repeated questions means the prefix stopped being
            # byte-stable — worth being able to see from the outside.
            "usage": totals,
        }

    return router
